"""
PowerPoint Report Generation Module
"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from datetime import datetime
from pathlib import Path
from src.config import PPTX_DIR, COMPANY_NAME, REPORT_AUTHOR


def create_pptx_report(summary_metrics, insights_text, chart_paths, output_filename=None):
    """
    Generate a comprehensive PowerPoint presentation.
    
    Args:
        summary_metrics: Dictionary of summary metrics
        insights_text: AI-generated insights text
        chart_paths: List of paths to chart images
        output_filename: Optional custom filename
    
    Returns:
        Path to generated PPTX file
    """
    if output_filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"campaign_report_{timestamp}.pptx"
    
    output_path = PPTX_DIR / output_filename
    
    # Create presentation
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Slide 1: Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Campaign Performance Report"
    subtitle.text = f"{COMPANY_NAME}\n{datetime.now().strftime('%B %d, %Y')}\n\nGenerated by {REPORT_AUTHOR}"
    
    # Slide 2: Key Metrics Overview
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    
    title = slide.shapes.title
    title.text = "Key Performance Metrics"
    
    # Add metrics as table
    rows = len(summary_metrics) + 1
    cols = 2
    
    left = Inches(1)
    top = Inches(2)
    width = Inches(8)
    height = Inches(4)
    
    table = slide.shapes.add_table(rows, cols, left, top, width, height).table
    
    # Set column widths
    table.columns[0].width = Inches(5)
    table.columns[1].width = Inches(3)
    
    # Header row
    table.cell(0, 0).text = "Metric"
    table.cell(0, 1).text = "Value"
    
    # Format header
    for i in range(cols):
        cell = table.cell(0, i)
        cell.fill.solid()
        cell.fill.fore_color.rgb = RGBColor(31, 119, 180)
        cell.text_frame.paragraphs[0].font.bold = True
        cell.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
        cell.text_frame.paragraphs[0].font.size = Pt(14)
    
    # Data rows
    for idx, (key, value) in enumerate(summary_metrics.items(), 1):
        key_formatted = key.replace('_', ' ').title()
        if isinstance(value, float):
            value_formatted = f"{value:,.2f}"
        else:
            value_formatted = f"{value:,}"
        
        table.cell(idx, 0).text = key_formatted
        table.cell(idx, 1).text = value_formatted
        
        # Alternate row colors
        if idx % 2 == 0:
            for col_idx in range(cols):
                cell = table.cell(idx, col_idx)
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(240, 240, 240)
    
    # Slide 3: Insights & Recommendations
    slide = prs.slides.add_slide(bullet_slide_layout)
    title = slide.shapes.title
    title.text = "AI-Powered Insights"
    
    body_shape = slide.placeholders[1]
    tf = body_shape.text_frame
    tf.clear()
    
    # Parse insights and add as bullet points
    current_section = None
    for line in insights_text.split('\n'):
        line = line.strip()
        if not line or line.startswith('='):
            continue
        
        if line.isupper() or any(line.startswith(word) for word in ['EXECUTIVE', 'KEY', 'ACTIONABLE', 'ROOT']):
            current_section = line
            p = tf.add_paragraph()
            p.text = line
            p.font.bold = True
            p.font.size = Pt(14)
            p.font.color.rgb = RGBColor(44, 160, 44)
            p.level = 0
        elif line and current_section:
            p = tf.add_paragraph()
            p.text = line.lstrip('•- ')
            p.font.size = Pt(12)
            p.level = 1
    
    # Slides 4+: Charts
    if chart_paths:
        for chart_path in chart_paths:
            chart_path = Path(chart_path)
            if chart_path.exists():
                try:
                    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
                    
                    # Add title
                    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.5))
                    title_frame = title_box.text_frame
                    title_frame.text = chart_path.stem.replace('_', ' ').title()
                    title_frame.paragraphs[0].font.size = Pt(24)
                    title_frame.paragraphs[0].font.bold = True
                    title_frame.paragraphs[0].font.color.rgb = RGBColor(31, 119, 180)
                    
                    # Add chart image
                    left = Inches(1)
                    top = Inches(1.2)
                    width = Inches(8)
                    
                    slide.shapes.add_picture(str(chart_path), left, top, width=width)
                    
                except Exception as e:
                    print(f"Warning: Could not add chart {chart_path}: {e}")
    
    # Save presentation
    prs.save(str(output_path))
    
    print(f"✓ PowerPoint report saved: {output_path}")
    return output_path


if __name__ == "__main__":
    # Test PPTX generation
    sample_metrics = {
        'total_campaigns': 5,
        'total_ads': 12,
        'total_spent': 5000.00,
        'total_conversions': 150,
        'avg_CTR': 3.5,
        'avg_CPC': 0.75
    }
    
    sample_insights = """
EXECUTIVE SUMMARY
Campaign performance shows strong engagement.

KEY FINDINGS
- CTR exceeds benchmarks
- Opportunities for optimization exist
"""
    
    pptx_path = create_pptx_report(sample_metrics, sample_insights, [])
    print(f"Test PPTX created: {pptx_path}")
